### PR TITLE
Fix import issue with part C5830143 from JLCPCB

### LINKED ISSUE #252: [C5830143] Failed to import from JLCPCB
I tried to import the part number C5830143 from JLCPCB, but it failed. Here's the error I got:
```
Failed to generate package from JLCPCB part: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "number",
    "path": [
      "dataStr",
      "head",
      "docType"
    ],
    "message": "Expected string, received number"
  },
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "string",
    "path": [
      "dataStr",
      "head",
      "utime"
    ],
    "message": "Expected number, received string"
  }
]
```

Could be an issue in `fetchEasyEDAComponent` or `convertRawEasyEdaToTs`

### PR DESCRIPTION
**Pull request by techmannih**
fix #252

### CODE REVIEW

File: scripts/add-test-for-part.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ it("should convert ${jlcpcbPartNumber} into typescript file", async () => {
 }
 
 // Check if a part number was provided as a command-line argument
-const partNumber = process.argv[2]
+const partNumber = "C5830143"
```
Comment (seveibar) [inline scripts/add-test-for-part.ts:64]: dude. READ YOUR PRS. Seriously, if you read your own code you would find these.

**Review by seveibar — CHANGES_REQUESTED** [review]
there's already a test for this- what was wrong with the component? It looks like it is already working?
